config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories
  has_many :products, through: :product_categories

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :product
  belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orders
  has_many :users, through: :orders

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

  belongs_to :product
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders


  def current_user_cart
    "cart#{id}"
  end

  def add_to_cart(product_id)
    $redis.hincrby current_user_cart, product_id, 1
  end

  def remove_from_cart(product_id)
    $redis.hdel current_user_cart, product_id
  end

  def remove_one_from_cart(product_id)
    $redis.hincrby current_user_cart, product_id, -1
  end

  def cart_count
    quantities = $redis.hvals "cart#{id}"
    quantities.reduce(0) { |sum, qty| sum + qty.to_i }
  end

  def cart_total_price
    get_cart_products_with_qty.map { |product, qty| product.price * qty.to_i }.reduce(:+)
  end

  def get_cart_products_with_qty
    cart_ids = []
    cart_qtys = []
    ($redis.hgetall current_user_cart).map do |key, value|
      cart_ids << key
      cart_qtys << value
    end
    cart_products = Product.find(cart_ids)
    cart_products.zip(cart_qtys)
  end

  def purchase_cart_products!
    get_cart_products_with_qty.each do |product, qty|
      self.orders.create(user: self, product: product, quantity: qty)
    end
    $redis.del current_user_cart
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :authenticate_admin!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category added!"
      redirect_to admin_categories_path
    else
      flash[:notice] = "Category can't be blank!"
      render 'admin/products/new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated!"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    Category.destroy(params[:id])
    flash[:notice] = "Category removed!"
    redirect_to admin_categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "Product added!"
      redirect_to admin_products_path
    else
      flash[:notice] = "Product can't be blank!"
      render 'admin/products/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      @product.product_categories.destroy_all
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "Product updated!"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    flash[:notice] = "Product removed!"
    redirect_to admin_products_path
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    current_user.add_to_cart(params[:product_id])
    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    redirect_to cart_path
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.all
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    before_action :authenticate_user!
    before_action :check_cart!

    def new
      gon.client_token = generate_client_token
    end

    def create
      @result = Braintree::Transaction.sale(
        amount: current_user.cart_total_price,
        payment_method_nonce: params[:payment_method_nonce])
      if @result.success?
        current_user.purchase_cart_products!
        flash[:notice] = "Congratulations! We'll try to get you your items as soon as possible!"
        redirect_to root_url
      else
        flash[:alert] = "Hmm, something went wrong, let's try again!"
        gon.client_token = generate_client_token
        render :new
      end
    end


    private

      def check_cart!
        if current_user.get_cart_products_with_qty.blank?
          redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
        end
      end

      def generate_client_token
        Braintree::ClientToken.generate
      end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/admin/categories/_admin_category.html.slim
tr
  td #{ admin_category.name }
  td = link_to 'Edit', edit_admin_category_path(admin_category)
  td = link_to 'Delete', admin_category_path(admin_category), method: :delete

app/views/admin/categories/edit.html.slim
h1.jumbotron Edit Category

.container
  = simple_form_for [:admin, @category], class: "form-horizontal" do |f|
    = f.input :name
    = f.button :submit

  = link_to 'Back to Category List', admin_categories_path

app/views/admin/categories/index.html.slim
h1.jumbotron Admin | Categories

.container
  .row
    = link_to 'Add Category', new_admin_category_path
    .col-12.card
      table.table
        thead
          th Name
        tbody
        = render partial: "admin_category", collection: @categories

app/views/admin/categories/new.html.slim
h1.jumbotron New Category

.container
  = simple_form_for [:admin, @category], class: "form-horizontal" do |f|
    = f.input :name
    = f.button :submit

  = link_to 'Back to Category List', admin_categories_path

app/views/admin/orders/_admin_order.html.slim
tr
  td #{ admin_order.user.email }
  td #{ admin_order.product.name }
  td #{ admin_order.quantity }
  td #{ admin_order.created_at.getlocal.strftime("%e-%m-%y %H:%M") }

app/views/admin/orders/index.html.slim
h1.jumbotron Admin | Orders

.container
  .row
    .col-12.card
      table.table
        thead
          th User
          th Product
          th Quantity
          th Order Time
        tbody
        = render partial: "admin_order", collection: @orders

app/views/admin/products/_admin_product.html.slim
tr
  td #{ admin_product.name }
  td #{ admin_product.description }
  td #{ admin_product.price }
  td = link_to 'Edit', edit_admin_product_path(admin_product)
  td = link_to 'Delete', admin_product_path(admin_product), method: :delete

app/views/admin/products/edit.html.slim
h1.jumbotron Edit Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price

    = f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false

    = f.button :submit

  = link_to 'Back to Product List', admin_products_path

app/views/admin/products/index.html.slim
h1.jumbotron Admin | Products

.container
  .row
    = link_to 'Add Product', new_admin_product_path
    .col-12.card
      table.table
        thead
          th Name
          th Description
          th Price
        tbody
        = render partial: "admin_product", collection: @products

app/views/admin/products/new.html.slim
h1.jumbotron Add a Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price
  
    = f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false

    = f.button :submit

  = link_to 'Back to Product List', admin_products_path

app/views/categories/show.html.slim
h1.jumbotron Shopping App | #{ @category.name }

.container
  .row
    = render partial: "shared/product", collection: @products

app/views/products/index.html.slim
h1.jumbotron Welcome to Shopping App!

.container
  .row
    = render partial: "shared/product", collection: @products

app/views/products/show.html.slim
h1.jumbotron #{ @product.name.capitalize }
.container
  .card
    .card-body
      p = @product.description
      p <small> SGD </small> #{ @product.price }
      = link_to 'Add to Cart', add_to_cart_path(@product), method: :put
    .card-footer
      = link_to 'Back to Product List', products_path