config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  resources :transactions, only: [:new, :create]

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories
  has_many :products, through: :product_categories

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :product
  belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :orders
  has_many :users, through: :orders

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

  belongs_to :product
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders


  def current_user_cart
    "cart#{id}"
  end

  def add_to_cart(product_id)
    $redis.hincrby current_user_cart, product_id, 1
  end

  def remove_from_cart(product_id)
    $redis.hdel current_user_cart, product_id
  end

  def remove_one_from_cart(product_id)
    $redis.hincrby current_user_cart, product_id, -1
  end

  def cart_count
    quantities = $redis.hvals "cart#{id}"
    quantities.reduce(0) { |sum, qty| sum + qty.to_i }
  end

  def cart_total_price
    get_cart_products_with_qty.map { |product, qty| product.price * qty.to_i }.reduce(:+)
  end

  def get_cart_products_with_qty
    cart_ids = []
    cart_qtys = []
    ($redis.hgetall current_user_cart).map do |key, value|
      cart_ids << key
      cart_qtys << value
    end
    cart_products = Product.find(cart_ids)
    cart_products.zip(cart_qtys)
  end

  def purchase_cart_products!
    get_cart_products_with_qty.each do |product, qty|
      self.orders.create(user: self, product: product, quantity: qty)
    end
    $redis.del current_user_cart
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    current_user.add_to_cart(params[:product_id])
    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    redirect_to cart_path
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.all
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    before_action :authenticate_user!
    before_action :check_cart!

    def new
      gon.client_token = generate_client_token
    end

    def create
      @result = Braintree::Transaction.sale(
        amount: current_user.cart_total_price,
        payment_method_nonce: params[:payment_method_nonce])
      if @result.success?
        current_user.purchase_cart_products!
        flash[:notice] = "Congratulations! We'll try to get you your items as soon as possible!"
        redirect_to root_url
      else
        flash[:alert] = "Hmm, something went wrong, let's try again!"
        gon.client_token = generate_client_token
        render :new
      end
    end


    private

      def check_cart!
        if current_user.get_cart_products_with_qty.blank?
          redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
        end
      end

      def generate_client_token
        Braintree::ClientToken.generate
      end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ShoppingAppRedo
    = csrf_meta_tags
    = include_gon
    script src="https://js.braintreegateway.com/v2/braintree.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar
      .container
        .navlink = link_to 'Home', products_path
        - Category.all.each do |category|
          .navlink = link_to category.name.capitalize, category_path(category)
        - unless user_signed_in?
          .navlink = link_to 'Login', new_user_session_path
        - if user_signed_in?
          .navlink = link_to 'Cart (' + "#{current_user.cart_count}" + ')', cart_path
          .navlink = link_to 'Logout', destroy_user_session_path
        - if admin_signed_in?
          h4 Admin
          .navlink = link_to 'Categories', admin_categories_path
          .navlink = link_to 'Products', admin_products_path
          .navlink = link_to 'Orders', admin_orders_path

    - flash.each do |name, msg|
       = content_tag :div, msg, class: name
    = yield

app/views/shared/_product.html.slim
.card
  .card-body
    .card-title
      p #{ product.name }
    .card-text
      p <small> SGD </small> #{ product.price }
    .card-footer
      = link_to 'View Product', product_path(product)